{
 "title": "Главный дашборд",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Очереди", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Work Items",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "work_items_queue_length{workitem_source_type=\"Type1\"}",
     "legendFormat": "{{workitem_source_type}}"
    },
    {
     "expr": "work_items_queue_length{workitem_source_type=\"Type2\"}",
     "legendFormat": "{{workitem_source_type}}"
    },
    {}
   ]
  },
  {
   "title": "Очередь work items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "work_items_queue_length", "legendFormat": "{{workitem_source_type}}" }
   ]
  },
  {
   "title": "Кол-во activities в ожидании",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "activity_queue_length{activity_uid=\"Main:Entry\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib1:Entry\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib1:A\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib1:B\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib1:C\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib1:D\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib2:Entry\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib2:A\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_queue_length{activity_uid=\"Lib2:B\"}",
     "legendFormat": "{{activity_uid}}"
    }
   ]
  },
  {
   "title": "Кол-во запущенных activities",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "activity_executing_count{activity_uid=\"Main:Entry\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib1:Entry\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib1:A\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib1:B\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib1:C\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib1:D\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib2:Entry\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib2:A\"}",
     "legendFormat": "{{activity_uid}}"
    },
    {
     "expr": "activity_executing_count{activity_uid=\"Lib2:B\"}",
     "legendFormat": "{{activity_uid}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Распределение времени выполнения activity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(activity_execution_time_bucket) by (le)",
     "legendFormat": "{{le}} sec"
    }
   ]
  },
  {
   "title": "Кол-во ошибок (общее)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(activity_error_count_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}