{
 "title": "Обработка Work Items",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "workitem_source_type", "label": "Тип источника данных", "query": "Type1,Type2" }
  ]
 },
 "panels": [
  { "title": "Work Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Состояние обработки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "work_items_queue_length{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "В очереди"
    },
    {
     "expr": "work_items_processed{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "Обработано"
    }
   ]
  },
  {
   "title": "График обработки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "work_items_queue_length{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "В очереди"
    },
    {
     "expr": "work_items_processed{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "Обработано"
    }
   ]
  },
  { "title": "Ошибки", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Общее кол-во ошибок по типам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(error_type) (activity_error_count_total{workitem_source_type=\"$workitem_source_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График ошибок по типам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "activity_error_count_total{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "{{activity_uid}}:{{error_type}}"
    }
   ]
  },
  {
   "title": "График ошибок по типу Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "repeat": "workitem_source_type",
   "targets": [
    {
     "expr": "activity_error_count_total{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "{{activity_uid}}"
    }
   ]
  },
  { "title": "Activity Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Распределение времени выполнения activity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (activity_execution_time_bucket{workitem_source_type=\"$workitem_source_type\"})",
     "legendFormat": "{{le}} sec"
    }
   ]
  },
  {
   "title": "Средняя длительность выполнения Activity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "avg  by (activity_uid) ((rate(activity_execution_time_sum{workitem_source_type=\"$workitem_source_type\"}[$__range])) / (rate(activity_execution_time_count{workitem_source_type=\"$workitem_source_type\"}[$__range])))",
     "legendFormat": "{{activity_uid}}"
    }
   ]
  },
  {
   "title": "Кол-во activities в ожидании",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "activity_queue_length{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "{{activity_uid}}"
    }
   ]
  },
  {
   "title": "Кол-во запущенных activities",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "activity_executing_count{workitem_source_type=\"$workitem_source_type\"}",
     "legendFormat": "{{activity_uid}}"
    }
   ]
  }
 ]
}