services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml      
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
    # command:
    #   - '--config.file=/etc/prometheus/prometheus.yml --enable-feature=otlp-write-receiver'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ../config/prometheus:/etc/prometheus
      - ../.data/prometheus:/prometheus