services:
  alertmanager:    
    container_name: alertmanager
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/alertmanager/Alertmanager.Dockerfile
    env_file:
      - .env
    ports:
      - 9093:9093
    restart: unless-stopped
    volumes:      
      - ../.data/alertmanager/:/etc/alertmanager/data/