version: "3"
services:

  prometheus:
    extends:
      file: docker-compose.prometheus.yml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.grafana.yml
      service: grafana

  jaeger:
    extends:
      file: docker-compose.jaeger.yml
      service: jaeger

  alertmanager:
    extends:
      file: docker-compose.alertmanager.yml
      service: alertmanager
