global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s 
otlp:
    # Ingest OTLP data keeping UTF-8 characters in metric/label names.
    translation_strategy: NoUTF8EscapingWithSuffixes
storage:
  exemplars:
    max_exemplars: 1000000

rule_files:
  - 'alert.rules.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
    scheme: http
    timeout: 10s
    api_version: v2
# scrape_configs:
# - job_name: prometheus
#   honor_timestamps: true
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - localhost:9090